import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { execFileSync } from "node:child_process";
import { parse } from "yaml";

const ROOT = process.cwd();
const SPEC_PATH = path.join(ROOT, "openapi", "mvp.yaml");
const GENERATED_DIR = path.join(ROOT, "src", "generated");
const TYPES_PATH = path.join(GENERATED_DIR, "api-types.ts");
const MOCKS_PATH = path.join(GENERATED_DIR, "api-mocks.ts");

function readSpec() {
  const raw = fs.readFileSync(SPEC_PATH, "utf8");
  return parse(raw);
}

function writeIfChanged(filePath, content) {
  if (fs.existsSync(filePath) && fs.readFileSync(filePath, "utf8") === content) {
    return false;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  return true;
}

function selectExample(jsonContent) {
  if (jsonContent.example) {
    return jsonContent.example;
  }
  if (jsonContent.examples && typeof jsonContent.examples === "object") {
    const first = Object.values(jsonContent.examples)[0];
    if (first && typeof first === "object" && "value" in first) {
      return first.value;
    }
  }
  return null;
}

function responseTypeFor(pathKey) {
  return `paths["${pathKey}"]["get"]["responses"]["200"]["content"]["application/json"]`;
}

function generateMocksModule(spec) {
  const endpoints = ["/api/models", "/api/orgs/{orgId}/usage", "/api/policies"];
  const exports = [];

  for (const endpoint of endpoints) {
    const jsonContent = spec.paths?.[endpoint]?.get?.responses?.["200"]?.content?.["application/json"];
    const example = jsonContent ? selectExample(jsonContent) : null;
    if (!example) {
      throw new Error(`Missing JSON example for ${endpoint}`);
    }

    const exportName =
      endpoint === "/api/models"
        ? "controlPlaneModelsMock"
        : endpoint === "/api/orgs/{orgId}/usage"
          ? "orgUsageMock"
          : "apiPoliciesListMock";

    exports.push(
      `export const ${exportName}: ${responseTypeFor(endpoint)} = ${JSON.stringify(example, null, 2)} as const;`
    );
  }

  return `// Generated by scripts/openapi/generate.mjs. Do not edit manually.\n` +
    `import type { paths } from "./api-types.js";\n\n` +
    exports.join("\n\n") +
    "\n";
}

fs.mkdirSync(GENERATED_DIR, { recursive: true });

execFileSync(
  process.platform === "win32" ? "npx.cmd" : "npx",
  ["openapi-typescript", SPEC_PATH, "-o", TYPES_PATH],
  { stdio: "inherit" }
);

const spec = readSpec();
const mocksContent = generateMocksModule(spec);
writeIfChanged(MOCKS_PATH, mocksContent);

console.log("[openapi] PASS generate artifacts");
